apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetdm.fullname" . }}-db
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
